input:
  type: kubernetes
  plugin:
    watches:
      - group: example.com
        version: v1
        kind: Bar

pipeline:
  processors:
    - bloblang: |
        let finalizer = "finalizer.bars.example.com"

        map finalizer {
          root = object
          metadata.finalizers = metadata.finalizers.or([]).append(finalizer)
        }

        root = match {
          meta().exists("deleted") || metadata.finalizers.or([]).contains($finalizer) => deleted()
          _ => {"object":this,"finalizer":$finalizer}.apply("finalizer")
        }

output:
  type: kubernetes
  plugin: {}

logger:
  level: info
