input:
  type: kubernetes
  plugin:
    watches:
      - group: example.com
        version: v1
        kind: Foo
        owns:
          - group: example.com
            version: v1
            kind: Bar

pipeline:
  processors:
    - bloblang: |
        root = match {
          meta().exists("deleted") => deleted()
        }

output:
  type: kubernetes_status
  plugin: {}
  processors:
    - bloblang: |
        root = this
        status.observedGeneration = metadata.generation
        status.lastReconciledAt = timestamp_utc("2006-01-02T15:04:05.999999999Z")
        status.status = match {
          metadata.exists("deletionTimestamp") => "Destroying"
          _ => "Reconciling"
        }

logger:
  level: info
