# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: benthos

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - id: benthos
    main: ./cmd/benthos/main.go
    goarch:
      - amd64
    goos:
      - linux
      - darwin
    env:
      - CGO_ENABLED=0

archives:
  - files:
      - none*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: cludden
    name: benthos-kubernetes

dockers:
  - binaries:
      - benthos
    builds:
      - benthos
    dockerfile: Dockerfile
    image_templates:
      - "cludden/benthos-kubernetes:latest"
      - "cludden/benthos-kubernetes:{{ .Tag }}"
      - "cludden/benthos-kubernetes:v{{ .Major }}"
